### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dsaf** [netonjm/ChipmunkSharp#1]
Hi!

It is very exciting to see a new physics engine being ported to C#!

However it is hard to figure out when to expect something usable/testable on NuGet and what is going on.

1) could you please post some sort of rough and short road map on the front page when you have a moment?

2) is it a learning exercise or driven by a commercial project? Any contact with the original Chipmunk company?

3) what platforms do you plan to target (e.g. when using MonoGame Vector2 should ideally replace cpVect instead of casting)?

4) what will be the best communication channel for non-issue type of questions?

5) do you plan to support it more actively than the author of Farseer updates his engine :)?

Thank you for your effort!

**Comment by netonjm** [comment]
Hi dsaf, 

There are two versions about ChipmunkSharp one based the C version and another based on JS port. 

At the moment two versions are "working" but on C version, collisions are not working correctly (was complicated understand the collision system) this is why I start JS based port. 
Javascript (in some cases) it's more friendly than C to understand.

1) Yes, no problem. I was busy finishing JS port this weekend and it's complicated get time for other tasks. But telling you clear, my next steps will be cleaning bugs on JS version, create some examples and in a short future update converge two versions to make and updated product.

2) This is not  a commercial it's a learning project for the love of C# language, and no I don't have any contact with the original Chipmunk company.

3) The reason about a cpVect and not Vector2 is to avoid any external class reference. Seems good idea implement extension methods to convert from cpVect to Vector2 or any framework you have.

I know the cast is unliked but it's the price to make a generic product on any C# environment.

4) Skype or IRC can be a good solution

5) ChipmunkSharp it's a Chipmunk port, and I will try to update sources every time I have time and feel like do it. 

Thanks!

**Comment by dsaf** [comment]
2) I meant if there is a particular project that drives this (e.g. a physics-heavy game that you want to make).

Fair enough!
